### ISSUE TITLE
direct test of julia_signal.jl fails

### ISSUE THREAD

**Issue by diam** [barche/QML.jl#18]
Bonjour,

I got last snapshot of QML on osx 10.9.5.
When I go in the distrib QML/test directory, the following commands are working:

    julia gui.jl
    julia image.jl

But the following one does not: the test seems to work (no error) but doesn't show anything and quit immediately.

    julia julia_signal.jl

-- Maurice
P.S: Thank you very much for this project, I'm not using it yet but I'm watching it and try the tests regularly .

**Comment by barche** [comment]
Hi Maurice,

This is the intended behavior :) The test just checks if the signal is received correctly by changing a value and checking that, no window is created in this case. The long-term plan is that all tests in the test directory should be runnable on something like Travis.

A more practical example using a signal is in `example/fizzbuzz.jl`, which is based on the FizzBuzz example from the Ruby QML bindings.

**Comment by diam** [comment]
Thank you very much for the reply.
I agree the `example` directory should be the first place to show "mini-applications" and `test` directory should be reserved for ....test!.

But the test directory is currently the more complete place where one can see Julia+QML codes. For example, the `gui.jl` code in test directory as more feature than the one in test direrctory.

Perhaps could you maintain some demos file in example that shows what can be currently build with le `QMJ.jl` package?

By the way

    julia example/repl-background.jl
    => Julia method  "pushdisplay"  returns unsupported  "Array"

and the `fizzbuzz.jl` doesn't seem to work (the label field is never updated):

    julia example/fizzbuzz.jl

**Comment by barche** [comment]
Yes, I should split up test/gui.jl and figure out a way to have an automated test for all functionality.

The most complete demos now are fizzbuzz and plot.jl (requires the Plots.jl and PyPlot.jl package). Does fizzbuzz not work if you enter 3, 5 or 15?

The repl-background is meant to be used like this after starting Julia, with Plots.jl installed
```
include("example/repl-background.jl")
plot([1,2],[3,4])
```

It should display the plot result in the QML window.

The warning about Array is harmless, since the return value is unused here (though I will have to add Array conversion sooner or later :)

**Comment by diam** [comment]
Hum, yes `fizzbuzz.jl` works (I entered some arbitrary text).
And `repl-background.jl` woks too in REPL mode.

Sorry for this bad issue report!
-- Maurice

**Comment by barche** [comment]
No worries, glad to hear it works :)
